tools:
  nodejs: 16.18.0
  npm: 8.19.2

envs:
  global:
    variables:
      APP_NAME: ALL #default value for all apps
      CONFIGURED_APPS:  #add app names here, this needs to be the same as conf.js -> testSuite
        - ALL
        - UFM
        - Monitor
        - Centrifuge
        - Portfolio
        
triggers:
  - push: disabled
  - manual:
      name: Run API Regression
      var(envr=qa)
      call: runUFMBeTests

parameters:
  - app: { type: string }

flows:
  default:
    - echo "IBG Test Suite!"
    - call: runAllTests
  concord-triggered-flow:
    - echo "Calling e2e flow from concord"
    - if: $app
      then:
      - echo "App found from Concord"
      - var(APP_NAME = '$app')
    - echo "Running for App -> $APP_NAME"
    - if: | #search app name here
       %{app =~ CONFIGURED_APPS}
      then:
      var(envr=qa)
      - call: runAllTests
      else:
      - echo "No matching app name was found. Exiting!!"
  runAllTests:
    try:
      - call: setup
      - ENV=${envr} TEST=regression  npm run tests:ufm-tests 
    finally:
      - call: reporter
  runUFMBeTests:
    try:
      - call: setup
      - ENV=${envr} TEST=regression  npm run tests:ufm-tests-be
    finally:
      - call: reporter
  runUFMSMokeTest:
    try:
      - call: setup
      - ENV=${envr} TEST=smoke  npm run tests:ufm-tests 
    finally:
      - call: reporter

  setup:
      - npm install
      - npx playwright install
  reporter:
    - publishReport:
        context: playwright
        dir: playwright-report
        index: index.html
        verbose: true

